---
kind: pipeline
type: docker
name: pipeline1

steps:
- name: greeting
  image: golang:1.12
  commands:
  - env
  - ls
  - sleep 10
  
- name: test
  image: golang:1.12
  commands:
  - pwd
  - whoami
  - sleep 5

- name: final
  image: golang:1.12
  commands:
  - echo "hello"
  depends_on:
  - greeting
  - test
  
---
kind: pipeline
type: docker
name: pipeline2
  
steps:
- name: foo
  image: golang:1.12
  commands:
  - echo "foo"
