---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - env
  - ls
  
- name: test
  image: golang:1.12
  commands:
  - pwd
  - whoami

- name: final
  image: golang:1.12
  commands:
  - go --verision
  depends_on:
  - greeting
  - final
