---
kind: pipeline
type: docker
name: pipeline1

steps:
- name: greeting
  image: golang:1.12
  commands:
  - env
  - ls
  
- name: test
  image: golang:1.12
  commands:
  - pwd
  - whoami

- name: final
  image: golang:1.12
  commands:
  - echo "hello"
  
  
---
kind: pipeline
type: docker
name: pipeline2
  
steps:
- name: foo
  image: golang:1.12
  commands:
  - echo "foo"
